on: [push]

jobs:
  rm_old_images:
    runs-on: ubuntu-latest
    name: A job to remove images
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: Remove the images
        uses: stevemar/image-deleter@v1.0.0
